name: Terminus Rsync Plugin
on: push
jobs:
  checkout_lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/php-ci:v7.4
    name: Checkout & lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save repo content as artifact
        uses: actions/upload-artifact@v2
        with:
          name: full-workspace
          path: ${{ github.workspace }}
      - name: Full Composer Install
        run: composer install
      - name: Install phpcs
        run: composer install-phpcs
      - name: Validate Code
        run: composer cs

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        php-versions: ['7.4', '8.2']
    container:
      image: pantheonpublic/terminus-plugin-test:4.x-php${{ matrix.php-versions }}
    name: Test (PHP ${{ matrix.php-versions }})
    needs: [ checkout_lint ]
    defaults:
      run:
        shell: bash
        working-directory: /terminus-plugin-test/plugin
    env:
      TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
      TERMINUS_SITE: ${{ secrets.TERMINUS_SITE }}
      BASH_ENV: ~/.bashrc
      HOME: /home/tester
    steps:
      - name: Download repo content from artifact
        uses: actions/download-artifact@v2
        with:
          name: full-workspace
          path: /terminus-plugin-test/plugin
      - name: Setup environment
        run: chmod +x ./.ci/set-up-globals.sh && ./.ci/set-up-globals.sh
      - name: Check Terminus version
        run: terminus --version
      - name: Install plugin
        run: terminus self:plugin:install .
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary
      - name: Run tests
        run: composer bats
